name: Lerna Test

on: [push, pull_request]

jobs:
  build:
    name: Node ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 12.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install lerna -g
      - run: lerna bootstrap --hoist
      - run: npm run test-ci
